version: '3'

services:
  rabbit1:
    image: harbur/rabbitmq-cluster
    hostname: rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
    ports:
      - "5672:5672"

  rabbit2:
    image: harbur/rabbitmq-cluster
    hostname: rabbit2
    links:
      - rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
      - CLUSTER_WITH=rabbit1
      - ENABLE_RAM=true
      - RAM_NODE=true
    ports:
      - "5673:5672"
